### ISSUE TITLE
Post page not showing up.

### ISSUE THREAD

**Issue by onabee** [onabee/project2#3]
This is the error I'm getting. 

```
NoMethodError at /post
undefined method `username' for nil:NilClass
file: post_page.erb location: block (2 levels) in singleton class line: 9
```

And here's the backtrace for that error 
```
/Users/ona/code/wdi/projects/project2/views/post_page.erb in block (2 levels) in singleton class
  <h2><%= comment.user.username %></h2>
/Users/ona/code/wdi/projects/project2/views/post_page.erb in block in singleton class
<% @comments.each do |comment| %>
/Users/ona/code/wdi/projects/project2/server.rb in block in <class:Server>
      erb :post_page
/Users/ona/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb in service
      si.service(req, res)
/Users/ona/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb in run
          server.service(req, res)
/Users/ona/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/server.rb in block in start_thread
          block ? block.call(sock) : run(sock)
```

Could you please look into my code and help me figure out what's wrong? I'm very confused because the whole comment.user.username worked in my category page when I did post.user.username so I don't know why it's not working here anymore.

**Comment by phlco** [comment]
```
<% @comments.each do |comment| %>
  <h2><%= comment.user.username %></h2>
  <img src="/<%= comment.user.avatar_img_url %>">
  <p><%= comment[:message] %>
<% end %>
```

It looks like you're calling `username` on the `user` object. A comment has a "user_id" which is how activerecord figures out what user object to return. Unless the comment doesn't have a user_id! 

It looks like you might have a comment without a user_id, in which case it returns nil, and then `username` gets called on nil and gives you an error.

**Comment by onabee** [comment]
Wait...do you still use the integer 0 fo the first index in a user_id? Cuz I've been doing that. Pretty sure that's why?

**Comment by phlco** [comment]
No, see your earlier issue. IDs start at 1 not 0. They're not arrays.  Don't hardcode in the IDs.  Instead use ActiveRecord.  Here's the difference:

```
User.create
Pet.create(user_id: 1) # this is hardcoded and assumes the above user is "1"
```
If you delete all the users your IDs won't reset, instead they'll start incrementing from where you left off, so rerunning would cause assignment to the wrong users.  Instead you'd want to do something like this:

```
user = User.create
Pet.create({user_id: user.id} #whatever the ID is of the user we just created.
```

**Comment by onabee** [comment]
Okay so I don't specify their id in the seeds?

**Comment by phlco** [comment]
Not directly. Just use the example from above as a guide.

**Comment by onabee** [comment]
Okay. Thank you.
